server:
  port: 8002

spring:
  profiles:
    active: dev
  application:
    name: payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    fetch-registry: true # 检索注册信息
    register-with-eureka: true #注册自己
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    # ip-address: 127.0.0.1
    instance-id: payment8002
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

