server:
  port: 9001

spring:
  application:
    name: NACOS-PAYMENT-SERVICE
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: info
