server:
  port: 3344

spring:
  profiles:
    active: dev
  application:
    name: CONFIG-SERVER-3344  # 应用名称
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/looyang/config.git #配置文件所在仓库
          default-label: master #默认git分支
          search-paths: springcloud  #代码仓中， 配置文件所在目录

logging:
  level:
    org.springframework: debug