server:
  port: 80

spring:
  application:
    name: NACOS-CONSUMER-SERVICE
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: info
