server:
  port: 7001

spring:
  application:
    name: eureka-server7001
  profiles:
    active: dev

eureka:
  instance:
    hostname: eureka7001.com
  client:
    fetch-registry: false #false表示自己端就是注册中心，职责就是维护服务实例，并不需要去检索服务
    register-with-eureka: false #false表示当前微服务不注册到eureka中(消费端)
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/ # 多实例

  server:
    #关闭自我保护机制，保证不可用服务立即被踢出
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 2000
    #不读取只读的缓存服务清单，因为30秒刷新一次比较慢，读写高速缓存过期策略
    use-read-only-response-cache: false

