server:
  port: 80

spring:
  application:
    name: consumer-service
  profiles:
    active: dev

logging:
  level:
    me.yangjun.study.springcloud: debug

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    ip-address: 127.0.0.1
    instance-id: consumer80
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

feign:
  hystrix:
    # 开启Hystrix
    enabled: true
  client:
    config:
      default:
        logger-level: BASIC