server:
  port: 80

spring:
  profiles:
    active: dev
  application:
    name: consumer-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    # ip-address: 127.0.0.1
    instance-id: consumer80
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

#设置feign客户端超时时间，单位毫秒
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 3000
