server:
  port: 80

spring:
  application:
    name: consumer-service

logging:
  level:
    me.yangjun.study.springcloud: debug

eureka:
  client:
    fetch-registry: true  #注册自己
    register-with-eureka: true # 检索注册信息，集群必须是true才能配合ribbon使用负载均衡
    registryFetchIntervalSeconds: 5 # 拉取间隔
    service-url:
       defaultZone: http://localhost:7001/eureka/
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    # ip-address: 127.0.0.1
    instance-id: consumer80
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

#设置feign客户端超时时间，单位毫秒
ribbon:
  ReadTimeout: 1000
  ConnectTimeout: 1000
