server:
  port: 8001

spring:
  profiles:
    active: dev
  application:
    name: payment-service

eureka:
  client:
    fetch-registry: true # 检索注册信息
    register-with-eureka: true #注册自己
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: payment8001
    # eureka网页显示ip链接
    # ip-address: 127.0.0.1
    prefer-ip-address: true
    # Eureka客户端向服务端发送信条的时间间隔，默认是30s
    lease-renewal-interval-in-seconds: 30
    # Eureka服务端收到最后一次心跳后等待时间上线，默认90s，如果服务端开始自我保护，超时将剔除该服务
    lease-expiration-duration-in-seconds: 90

