spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.1.1:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Aa123456

logging:
  level:
    root: info

eureka:
  client:
    service-url:
       defaultZone: http://localhost:7001/eureka/
