server:
  port: 8003

spring:
  profiles:
    active: dev
  application:
    name: payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
  cloud:
    zookeeper:
      connect-string: 000.000.000:2181
